src/main/java/com/Bridge/bridge/domain/SearchWord.java, src/main/java/com/Bridge/bridge/domain/StaticMessage.java, src/main/java/com/Bridge/bridge/domain/User.java
- 지정 메세지 테이블 생성 및 유저와의 연관관계 설정
- 검색어 테이블 생성 및 유저와의 연관관계 설정
- 유저가 직접 만든 지정 메세지는 테이블에 담고, 본래 프로그램에 있던 지정메세지는 enum 으로 관리하는게 좋을 것 같습니다. 
- 검색어 테이블을 만든 이유는 단순하게 '최근 검색어' 목록을 불러오기 위함입니다.
=> [23-08-25] kyuhyun 

.gitignore, src/main/java/com/Bridge/bridge/domain/Part.java, src/main/java/com/Bridge/bridge/domain/Project.java
- 프로젝트 테이블 중 <모집분야,모집인원> 부분 관련 속성 수정
- Part(Embedded 객체) 생성
- 모집분야와 모집인원에서의 수정은 거의 없을 것 같아 일대다 관계를 위한 엔티티 생성 대신 
값 타입 컬렉션과 임베디드 타입을 이용하는 방식(중간에 테이블 하나 더 생성X)으로 하였습니다.
=> FIX : Project 테이블 속성 변경 및 연관관계 수정

src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/domain/Part.java, src/main/java/com/Bridge/bridge/domain/Project.java, src/main/java/com/Bridge/bridge/domain/User.java, src/main/java/com/Bridge/bridge/dto/request/FilterRequestDto.java, src/main/java/com/Bridge/bridge/dto/request/PartRequestDto.java, src/main/java/com/Bridge/bridge/dto/request/ProjectRequestDto.java, src/main/java/com/Bridge/bridge/dto/response/PartResponseDto.java, src/main/java/com/Bridge/bridge/dto/response/ProjectListResponseDto.java, src/main/java/com/Bridge/bridge/dto/response/ProjectResponseDto.java, src/main/java/com/Bridge/bridge/repository/PartRepository.java, src/main/java/com/Bridge/bridge/repository/ProjectRepository.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java
- 프로젝트 상세보기 기능
- 프로젝트 필터링(관심분야, 관심스킬) 기능
- 프로젝트 수정 return값 projectId로 변경 완료
- 피그마에서 프로젝트 필터링 기능에서 관심분야는 한 번에 하나만 선택할 수 있는 것 처럼 보여서 관심분야는 한 개만, 관심 스킬은 여러개 받을 수 있게 구현했습니다.
- 지난 PR 머지 후 push 했어야 하는데 모르고 push 먼저해서 되돌린 다음에 다시 push 하느라 commit message가 중복된 것이 조금 있습니다.
=> [230922] Jimin

build.gradle, src/main/java/com/Bridge/bridge/config/S3Config.java, src/main/java/com/Bridge/bridge/controller/AuthController.java, src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/controller/UserController.java, src/main/java/com/Bridge/bridge/domain/ApplyProject.java, src/main/java/com/Bridge/bridge/domain/File.java, src/main/java/com/Bridge/bridge/domain/Profile.java, src/main/java/com/Bridge/bridge/dto/response/UserProfileResponse.java, src/main/java/com/Bridge/bridge/exception/badrequest/FileDeleteException.java, src/main/java/com/Bridge/bridge/exception/badrequest/FileUploadException.java, src/main/java/com/Bridge/bridge/exception/notfound/NotFoundFileException.java, src/main/java/com/Bridge/bridge/exception/notfound/NotFoundProfileException.java, src/main/java/com/Bridge/bridge/repository/FileRepository.java, src/main/java/com/Bridge/bridge/service/FileService.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/main/java/com/Bridge/bridge/service/UserService.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java, src/test/java/com/Bridge/bridge/controller/UserControllerTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java, src/test/java/com/Bridge/bridge/service/UserServiceTest.java
- 유저 프로필 조회 기능
- 프로젝트 수락 기능
- 프로젝트 거절 기능
- s3 파일 서비스
- 채팅에서의 파일 업로드는 조금 더 공부 해봐야 할 것 같아요🥲
=> [23-10-13] kyuhyun

src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/domain/Project.java, src/main/java/com/Bridge/bridge/dto/request/ProjectRequestDto.java, src/main/java/com/Bridge/bridge/dto/request/ProjectUpdateRequestDto.java, src/main/java/com/Bridge/bridge/repository/ProjectRepository.java, src/main/java/com/Bridge/bridge/security/JwtTokenProvider.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java
- 모집글 수정, 삭제, 마감 권한 
- 모집글 상세보기에 isMyProject 필드 추가
- 없습니다!,,
=> [23-10-21] Kyuhyun

src/main/java/com/Bridge/bridge/config/FCMConfig.java, src/main/java/com/Bridge/bridge/controller/AlarmController.java, src/main/java/com/Bridge/bridge/controller/ChatMessageController.java, src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/domain/Alarm.java, src/main/java/com/Bridge/bridge/domain/Project.java, src/main/java/com/Bridge/bridge/domain/User.java, src/main/java/com/Bridge/bridge/dto/request/ProjectRequestDto.java, src/main/java/com/Bridge/bridge/dto/request/ProjectUpdateRequestDto.java, src/main/java/com/Bridge/bridge/dto/response/AllAlarmResponse.java, src/main/java/com/Bridge/bridge/dto/response/ApplyProjectResponse.java, src/main/java/com/Bridge/bridge/dto/response/imminentProjectResponse.java, src/main/java/com/Bridge/bridge/exception/badrequest/AlarmDeleteException.java, src/main/java/com/Bridge/bridge/exception/notfound/NotFoundAlarmException.java, src/main/java/com/Bridge/bridge/repository/AlarmRepository.java, src/main/java/com/Bridge/bridge/repository/ProjectRepository.java, src/main/java/com/Bridge/bridge/service/AlarmService.java, src/main/java/com/Bridge/bridge/service/FCMService.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/controller/AlarmControllerTest.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java, src/test/java/com/Bridge/bridge/service/AlarmServiceTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java
- 알림 목록 조회
- 전체 알림 삭제 
- 마감 임박 40개 프로젝트 조회
- 시간 관련 속성(uploadTime, dueDate, startDate, endDate) 자료형 모두 String -> LocalDateTime으로 변경
- Alarm 객체 생성
시간 관련 속성을 일단 자료형 변경을 하면서 생기는 오류를 최대한 수정한다고 했는데, 
혹시 보면서 이상한 점 알려주시면 감사하겠습니다~!
=> [23-10-27] Jimin

build.gradle, src/main/java/com/Bridge/bridge/controller/UserController.java, src/main/java/com/Bridge/bridge/dto/response/BookmarkListResponse.java, src/main/java/com/Bridge/bridge/service/UserService.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java, src/test/java/com/Bridge/bridge/controller/UserControllerTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java, src/test/java/com/Bridge/bridge/service/UserServiceTest.java
- 회원 탈퇴 기능
- 여러 오류 수정
- 이거랑 지민님꺼 머지한 후 바로 배포할게요~!
=> [23-11-03] KyuHyun

src/main/java/com/Bridge/bridge/dto/response/BookmarkListResponse.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java
=> FIX : 오류수정

appspec.yml, scripts/start.sh, scripts/stop.sh
=> FEAT : 배포 관련 파일

appspec.yml, scripts/start.sh, scripts/stop.sh
=> FIX : 배포 관련 파일 수정

src/main/java/com/Bridge/bridge/config/AuthConfig.java
=> TEST : 채팅방 목록 조회 시 인증

src/main/java/com/Bridge/bridge/controller/AuthController.java
=> FIX : 회원가입 오류 수정

src/main/java/com/Bridge/bridge/dto/response/OAuthTokenResponse.java, src/main/java/com/Bridge/bridge/service/AuthService.java
=> REFACTOR : 회원가입 시 유저ID 반환

.github/workflows/main.yml, .gitignore, src/main/java/com/Bridge/bridge/service/AuthService.java
=> FIX : 로직 수정 및 배포 관련 파일 수정

src/main/java/com/Bridge/bridge/config/WebSocketConfig.java, src/main/java/com/Bridge/bridge/controller/UserController.java, src/main/java/com/Bridge/bridge/dto/response/MyPageResponse.java, src/main/java/com/Bridge/bridge/security/JwtTokenProvider.java, src/main/java/com/Bridge/bridge/service/UserService.java, src/test/java/com/Bridge/bridge/controller/UserControllerTest.java, src/test/java/com/Bridge/bridge/service/UserServiceTest.java
=> [23-11-10] Kyuhyun

src/main/java/com/Bridge/bridge/config/WebSocketConfig.java, src/main/java/com/Bridge/bridge/controller/ChatController.java, src/main/java/com/Bridge/bridge/dto/response/ChatRoomResponse.java, src/main/java/com/Bridge/bridge/security/ChannelInBoundInterceptor.java, src/main/java/com/Bridge/bridge/security/JwtTokenProvider.java, src/main/java/com/Bridge/bridge/service/ChatService.java, src/test/java/com/Bridge/bridge/service/ChatServiceTest.java
=> [23-11-16] Kyuhyun

src/main/java/com/Bridge/bridge/controller/ChatMessageController.java, src/main/java/com/Bridge/bridge/domain/Chat.java, src/main/java/com/Bridge/bridge/domain/Message.java, src/main/java/com/Bridge/bridge/dto/request/ChatMessageRequest.java, src/main/java/com/Bridge/bridge/dto/response/ChatListResponse.java, src/main/java/com/Bridge/bridge/dto/response/ChatMessageResponse.java, src/main/java/com/Bridge/bridge/security/ChannelInBoundInterceptor.java, src/main/java/com/Bridge/bridge/service/ChatService.java, src/test/java/com/Bridge/bridge/service/ChatServiceTest.java
- 채팅방 읽음 처리
- 수락, 거절 메세지
- 채팅방 목록 조회 시 안읽은 메세지 개수
- 현재 미접속 시 알림발송
- 알람서비스 기능을 ChatService 쪽으로 이동했어요!
=> [23-11-17] Kyuhyun

src/main/java/com/Bridge/bridge/controller/ChatMessageController.java, src/main/java/com/Bridge/bridge/dto/response/ChatListResponse.java, src/main/java/com/Bridge/bridge/security/ChannelInBoundInterceptor.java, src/main/java/com/Bridge/bridge/service/ChatService.java
=> [23-11-18] Kyuhyun

src/main/java/com/Bridge/bridge/domain/Stack.java
=> FIX : domain_stack 오타 수정

src/main/java/com/Bridge/bridge/controller/ChatMessageController.java, src/main/java/com/Bridge/bridge/domain/Message.java, src/main/java/com/Bridge/bridge/dto/request/ChatMessageRequest.java, src/main/java/com/Bridge/bridge/dto/response/ChatListResponse.java, src/main/java/com/Bridge/bridge/dto/response/ChatMessageResponse.java, src/main/java/com/Bridge/bridge/security/ChannelInBoundInterceptor.java, src/main/java/com/Bridge/bridge/service/ChatService.java, src/test/java/com/Bridge/bridge/service/ChatServiceTest.java
=> [23-11-22] Kyuhyun

src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/dto/response/ChatListResponse.java, src/main/java/com/Bridge/bridge/security/ChannelInBoundInterceptor.java, src/main/java/com/Bridge/bridge/service/ChatService.java, src/test/java/com/Bridge/bridge/controller/ChatControllerTest.java, src/test/java/com/Bridge/bridge/service/ChatServiceTest.java
- 채팅방 메세지 업데이트 로직 변경
- 프로젝트 생성 시 ID 반환 -> JSON
- 테스트 오류 수정
=> [23-11-23] Kyuhyun

src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/service/ProjectService.java
- 모집글 조회 관련 기능 구현에서 모집인원 로직 수정
- 스웨거 기능명 수정
=> [23-11-26] Jimin

src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/dto/request/myPartProjectRequest.java, src/main/java/com/Bridge/bridge/service/ProjectService.java
=> Fix : 내 분야 모집글 Request 형식 변경

src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/dto/response/TopProjectResponseDto.java, src/main/java/com/Bridge/bridge/dto/response/imminentProjectResponse.java, src/main/java/com/Bridge/bridge/service/ProjectService.java
- 인기글 순, 마감 순 모집글들 조회 기능에서 projectId, recruitNum 속성 추가
- Api 주소 연결 오류 수정
=> [23-11-27] Jimin

build.gradle, src/main/java/com/Bridge/bridge/config/kafka/ConsumerConfig.java, src/main/java/com/Bridge/bridge/config/kafka/ProducerConfig.java, src/main/java/com/Bridge/bridge/controller/ChatController.java, src/main/java/com/Bridge/bridge/controller/ChatMessageController.java, src/main/java/com/Bridge/bridge/domain/Alarm.java, src/main/java/com/Bridge/bridge/domain/Chat.java, src/main/java/com/Bridge/bridge/domain/Message.java, src/main/java/com/Bridge/bridge/domain/Part.java, src/main/java/com/Bridge/bridge/dto/request/ChatMessageRequest.java, src/main/java/com/Bridge/bridge/dto/response/ChatHistoryResponse.java, src/main/java/com/Bridge/bridge/dto/response/ChatMessageResponse.java, src/main/java/com/Bridge/bridge/security/ChannelInBoundInterceptor.java, src/main/java/com/Bridge/bridge/service/ChatService.java, src/main/java/com/Bridge/bridge/service/MessageReceiver.java, src/main/java/com/Bridge/bridge/service/MessageSender.java, src/main/java/com/Bridge/bridge/util/Constant.java, src/test/java/com/Bridge/bridge/service/ChatServiceTest.java
=> [23-12-02] kyuhyun

README.md, src/main/java/com/Bridge/bridge/config/kafka/ConsumerConfig.java, src/main/java/com/Bridge/bridge/config/kafka/ProducerConfig.java, src/main/java/com/Bridge/bridge/dto/response/ApplyProjectResponse.java, src/main/java/com/Bridge/bridge/service/ChatService.java, src/main/java/com/Bridge/bridge/util/Constant.java
=> [23-12-07] Kyuhyun

src/main/java/com/Bridge/bridge/service/ChatService.java
=> 알람 관련 기능 주석 해제

README.md, src/main/java/com/Bridge/bridge/dto/response/MyPageResponse.java, src/main/java/com/Bridge/bridge/service/UserService.java, src/test/java/com/Bridge/bridge/service/UserServiceTest.java
=> [23-12-13] Kyuhyun 

src/main/java/com/Bridge/bridge/config/FCMConfig.java, src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/service/AlarmServiceTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java
=> FCM 관련 json 파일 변경

src/main/java/com/Bridge/bridge/controller/AlarmController.java, src/main/java/com/Bridge/bridge/controller/UserController.java, src/main/java/com/Bridge/bridge/domain/User.java, src/main/java/com/Bridge/bridge/dto/request/FieldUpdateRequest.java, src/main/java/com/Bridge/bridge/dto/response/OAuthTokenResponse.java, src/main/java/com/Bridge/bridge/dto/response/apple/AppleMemberResponse.java, src/main/java/com/Bridge/bridge/dto/response/apple/AppleResponse.java, src/main/java/com/Bridge/bridge/repository/UserRepository.java, src/main/java/com/Bridge/bridge/security/apple/AppleUtils.java, src/main/java/com/Bridge/bridge/service/AlarmService.java, src/main/java/com/Bridge/bridge/service/AuthService.java, src/main/java/com/Bridge/bridge/service/UserService.java, src/test/java/com/Bridge/bridge/controller/AlarmControllerTest.java, src/test/java/com/Bridge/bridge/controller/ChatControllerTest.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java, src/test/java/com/Bridge/bridge/controller/SearchWordControllerTest.java, src/test/java/com/Bridge/bridge/controller/UserControllerTest.java, src/test/java/com/Bridge/bridge/security/JwtTokenProviderTest.java, src/test/java/com/Bridge/bridge/service/AlarmServiceTest.java, src/test/java/com/Bridge/bridge/service/AuthServiceTest.java, src/test/java/com/Bridge/bridge/service/ChatServiceTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java, src/test/java/com/Bridge/bridge/service/SearchWordServiceTest.java, src/test/java/com/Bridge/bridge/service/UserServiceTest.java
- 디바이스 토큰 로그인 시 전달
- 유저 Email 필드 삭제
- 관심분야 수정 로직 추가
=> [23-12-17] Kyuhyun

src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/domain/Part.java, src/main/java/com/Bridge/bridge/domain/Project.java, src/main/java/com/Bridge/bridge/service/ProjectService.java
=> FIX : 모집글 상세보기 - Response에서 시작, 종료 날짜 null일 때 예외처리 & Request parameter 자료형 변경

src/main/java/com/Bridge/bridge/controller/ProjectController.java
=> FIX : 모집글 마감하기 parameter 자료형 변경

src/main/java/com/Bridge/bridge/controller/ProjectController.java
=> FIX : 모집글 상세보기 - Request Parameter 변경

src/main/java/com/Bridge/bridge/dto/request/ChatRoomRequest.java, src/main/java/com/Bridge/bridge/service/ChatService.java
=> REFACTOR : 채팅방 생성 로직 수정

src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/test/java/com/Bridge/bridge/service/AlarmServiceTest.java
- jwt 받을 필요 없이 프로젝트 지원자의 ID와 프로젝트 ID만 받으면 될 것 같아 이렇게 다시 변경하였습니다.
=> FIX : 프로젝트 지원 수락 & 거절 Request Parameter 변경

src/main/java/com/Bridge/bridge/domain/Stack.java
=> FIX : Stack 변경

src/main/java/com/Bridge/bridge/domain/Project.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java
=> FIX : 모집글 상세보기 - 스크랩 여부 로직 수정

src/main/java/com/Bridge/bridge/dto/response/MyProjectResponseDto.java, src/main/java/com/Bridge/bridge/service/AlarmService.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/service/AlarmServiceTest.java
=> 알람 & 내가 작성한 프로젝트 Status 워딩 변경

src/main/java/com/Bridge/bridge/domain/Part.java, src/main/java/com/Bridge/bridge/dto/request/NotificationRequestDto.java, src/main/java/com/Bridge/bridge/dto/request/PartRequestDto.java, src/main/java/com/Bridge/bridge/dto/response/BookmarkListResponse.java, src/main/java/com/Bridge/bridge/dto/response/PartResponseDto.java, src/main/java/com/Bridge/bridge/service/AlarmService.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java, src/test/java/com/Bridge/bridge/service/UserServiceTest.java
- 북마크 디데이 추가
- 북마크 프로젝트 시작-끝 수정
- 모집의 모집분야 String -> Enum으로 수정
- 테스트 수정
=> [23-12-23] Kyuhyun

src/main/java/com/Bridge/bridge/repository/PartRepository.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/service/AlarmServiceTest.java
=> FIX : PartRepository - 모집분야 별 프로젝트 찾기 파라미터 자료형 Field로 변경

src/main/java/com/Bridge/bridge/service/ProjectService.java
=> FIX : 지원자 목록 조회 NPE 수정

src/main/java/com/Bridge/bridge/repository/ChatRepository.java, src/main/java/com/Bridge/bridge/service/ChatService.java, src/test/java/com/Bridge/bridge/service/ChatServiceTest.java
=> FIX : 채팅방 중복 체크 수정

src/main/java/com/Bridge/bridge/domain/Project.java, src/main/java/com/Bridge/bridge/dto/request/ProjectRequestDto.java, src/main/java/com/Bridge/bridge/dto/response/ApplyProjectResponse.java, src/main/java/com/Bridge/bridge/dto/response/ApplyUserResponse.java, src/main/java/com/Bridge/bridge/repository/PartRepository.java, src/main/java/com/Bridge/bridge/repository/ProjectRepository.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java, src/test/java/com/Bridge/bridge/controller/UserControllerTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java, src/test/java/com/Bridge/bridge/service/UserServiceTest.java
=> [24-01-02] Kyuhyun

src/main/java/com/Bridge/bridge/domain/Profile.java, src/main/java/com/Bridge/bridge/domain/Project.java, src/main/java/com/Bridge/bridge/dto/response/BookmarkListResponse.java, src/main/java/com/Bridge/bridge/dto/response/MyPageResponse.java, src/main/java/com/Bridge/bridge/service/MessageReceiver.java, src/main/java/com/Bridge/bridge/service/UserService.java, src/test/java/com/Bridge/bridge/service/UserServiceTest.java
=> [24-01-08] Kyuhyun

src/main/java/com/Bridge/bridge/controller/ProjectController.java, src/main/java/com/Bridge/bridge/controller/SearchWordController.java, src/main/java/com/Bridge/bridge/domain/Part.java, src/main/java/com/Bridge/bridge/domain/Project.java, src/main/java/com/Bridge/bridge/dto/request/FilterRequest.java, src/main/java/com/Bridge/bridge/dto/request/MyPartProjectRequest.java, src/main/java/com/Bridge/bridge/dto/request/NotificationRequest.java, src/main/java/com/Bridge/bridge/dto/request/PartRequest.java, src/main/java/com/Bridge/bridge/dto/request/ProjectRequest.java, src/main/java/com/Bridge/bridge/dto/request/ProjectUpdateRequest.java, src/main/java/com/Bridge/bridge/dto/response/BookmarkResponse.java, src/main/java/com/Bridge/bridge/dto/response/MyProjectResponse.java, src/main/java/com/Bridge/bridge/dto/response/PartResponse.java, src/main/java/com/Bridge/bridge/dto/response/ProjectListResponse.java, src/main/java/com/Bridge/bridge/dto/response/ProjectResponse.java, src/main/java/com/Bridge/bridge/dto/response/SearchWordResponse.java, src/main/java/com/Bridge/bridge/dto/response/TopProjectResponse.java, src/main/java/com/Bridge/bridge/service/AlarmService.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/main/java/com/Bridge/bridge/service/SearchWordService.java, src/main/java/com/Bridge/bridge/util/Constant.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java, src/test/java/com/Bridge/bridge/service/SearchWordServiceTest.java
=> REFACTOR : 네이밍 변경

src/main/java/com/Bridge/bridge/controller/UserController.java, src/main/java/com/Bridge/bridge/domain/File.java, src/main/java/com/Bridge/bridge/domain/Message.java, src/main/java/com/Bridge/bridge/domain/Profile.java, src/main/java/com/Bridge/bridge/domain/User.java, src/main/java/com/Bridge/bridge/dto/request/ProfileUpdateRequest.java, src/main/java/com/Bridge/bridge/dto/request/UserProfileRequest.java, src/main/java/com/Bridge/bridge/dto/response/FileResponse.java, src/main/java/com/Bridge/bridge/dto/response/UserProfileResponse.java, src/main/java/com/Bridge/bridge/service/FileService.java, src/main/java/com/Bridge/bridge/service/UserService.java, src/test/java/com/Bridge/bridge/controller/UserControllerTest.java, src/test/java/com/Bridge/bridge/security/JwtTokenProviderTest.java, src/test/java/com/Bridge/bridge/service/AlarmServiceTest.java, src/test/java/com/Bridge/bridge/service/UserServiceTest.java
- 첨부 링크, 첨부 파일 리스트로 받기
- 기존 파일 지우지 않고 원하는 것만 업데이트
- 안쓰는 연관관계 삭제
=> [24-01-11] kyuhyun

src/test/java/com/Bridge/bridge/service/AlarmServiceTest.java
=> FIX : AlarmServiceTest 주석 제거 & 디바이스 토큰 노출 해결

build.gradle, src/main/java/com/Bridge/bridge/config/FCMConfig.java, src/main/java/com/Bridge/bridge/service/ChatService.java, src/test/java/com/Bridge/bridge/controller/ChatControllerTest.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java
- 테스트 시  firebase 객체 반복 생성 수정
- 롬복 의존성 추가
- 테스트 수정
=> [24-01-18] Kyuhyun

src/main/java/com/Bridge/bridge/domain/FieldAndStack.java, src/main/java/com/Bridge/bridge/domain/Profile.java, src/main/java/com/Bridge/bridge/dto/request/FieldAndStackRequest.java, src/main/java/com/Bridge/bridge/dto/request/ProfileUpdateRequest.java, src/main/java/com/Bridge/bridge/dto/request/UserProfileRequest.java, src/main/java/com/Bridge/bridge/dto/response/FieldAndStackResponse.java, src/main/java/com/Bridge/bridge/dto/response/UserProfileResponse.java, src/main/java/com/Bridge/bridge/service/UserService.java, src/test/java/com/Bridge/bridge/controller/UserControllerTest.java, src/test/java/com/Bridge/bridge/service/AuthServiceTest.java, src/test/java/com/Bridge/bridge/service/UserServiceTest.java
=> [24-01-23] Kyuhyun

src/main/java/com/Bridge/bridge/domain/User.java, src/main/java/com/Bridge/bridge/dto/request/ProfileUpdateRequest.java, src/main/java/com/Bridge/bridge/service/UserService.java
=> REFACTOR : 프로필 유저 이름 수정 추가

src/test/java/com/Bridge/bridge/controller/ChatControllerTest.java, src/test/java/com/Bridge/bridge/controller/ProjectControllerTest.java, src/test/java/com/Bridge/bridge/security/JwtTokenProviderTest.java, src/test/java/com/Bridge/bridge/service/ChatServiceTest.java
=> Test : 테스트 오류 수정

src/main/java/com/Bridge/bridge/dto/request/UserProfileRequest.java, src/main/java/com/Bridge/bridge/dto/response/ApplyUserResponse.java, src/main/java/com/Bridge/bridge/dto/response/ChatRoomResponse.java, src/main/java/com/Bridge/bridge/service/ChatService.java, src/main/java/com/Bridge/bridge/service/UserService.java
- 지원자 목록 반환 시 프로필 사진 Url 반환
- 채팅방 개설 시  프로필 사진 Url 반환
- 프로필 등록 시 이름 추가
=> [24-01-29] kyuhyun

src/main/java/com/Bridge/bridge/domain/Profile.java
=> REFACTOR : 프로필 수정 시 빈 배열인 경우

src/main/java/com/Bridge/bridge/config/FCMConfig.java, src/main/java/com/Bridge/bridge/controller/SearchWordController.java, src/main/java/com/Bridge/bridge/repository/SearchWordRepository.java, src/main/java/com/Bridge/bridge/service/AlarmService.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/main/java/com/Bridge/bridge/service/SearchWordService.java, src/test/java/com/Bridge/bridge/controller/SearchWordControllerTest.java, src/test/java/com/Bridge/bridge/service/AlarmServiceTest.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java, src/test/java/com/Bridge/bridge/service/SearchWordServiceTest.java
- 유저가 검색한 검색어 전체 삭제 기능 구현
- 테스트 코드 일부 삭제
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
=> 전체 검색어 삭제 기능 구현 & 테스트 코드 일부 수정

src/main/java/com/Bridge/bridge/repository/SearchWordRepository.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/main/java/com/Bridge/bridge/service/SearchWordService.java, src/test/java/com/Bridge/bridge/service/SearchWordServiceTest.java
=> 최근 검색어 조회 기능 관련 수정

src/main/java/com/Bridge/bridge/domain/Project.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java
=> FIX : ProjectResponse - LocalDateTime 초 단위가 무조건 출력되도록 수정

src/main/java/com/Bridge/bridge/config/AuthConfig.java
=> FEAT : 유저 권한 검사 추가

src/main/java/com/Bridge/bridge/config/AuthConfig.java
=> FIX : 유저 권한 검사 수정

src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java
=> FIX : 날짜 관련 속성 0초여도 출력되도록 수정

src/main/java/com/Bridge/bridge/config/AuthConfig.java, src/main/java/com/Bridge/bridge/controller/UserController.java, src/main/java/com/Bridge/bridge/dto/response/BookmarkListResponse.java
=> FIX : 오류 수정

src/main/java/com/Bridge/bridge/exception/conflict/ConflictApplyProjectException.java, src/main/java/com/Bridge/bridge/service/ProjectService.java, src/test/java/com/Bridge/bridge/service/ProjectServiceTest.java
- 프로젝트 중복 지원 시 예외 반환
- 에러코드는 409 로 설정했습니다!
=> FEAT : 모집글 중복 지원 불가 
